name: Deploy to VPS

on:
  # Triggers the workflow on push events to the main branch
  push:
    branches: [main]

jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # This step connects to your VPS via SSH and runs the deployment script.
      - name: Trigger deployment script on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          # Your VPS IP address or hostname
          host: ${{ secrets.VPS_HOST }}

          # The username for your VPS
          username: ${{ secrets.VPS_USER }}

          # The private SSH key to authenticate
          key: ${{ secrets.DEPLOY_KEY }}

          # The SSH port, default is 22
          port: 22

          # The command to run on the VPS.
          # It navigates to the script's directory and executes it.
          script: |
            cd /srv/asdesigns
            bash ./deploy.sh
